repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
        args: [--max-line-length=99]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8.2
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3d68da9e8ee7b22ab8f516ed393ff01a90001d22
    hooks:
      - id: flake8
        args: [--max-line-length=99]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: f687d36b12cd72d417bba07599ff27e734161768
    hooks:
      - id: mypy
